### ISSUE TITLE
using version: latest in the sauceConnectOpts fails with a file error

### ISSUE THREAD

**Issue by nwwells** [webdriverio/wdio-sauce-service#24] opened 2017-04-26 03:52 UTC
```
Missing Sauce Connect local proxy, downloading dependency
This will only happen once.
Downloading 7.16MB
Checksum check for manually overwritten sc version isn't supported.
Unzipping /Users/nathan/Projects/symbiont/wdio-cuke/uat/node_modules/sauce-connect-launcher/sc/sc-latest-osx.zip
Removing /Users/nathan/Projects/symbiont/wdio-cuke/uat/node_modules/sauce-connect-launcher/sc/sc-latest-osx.zip
Sauce Connect downloaded correctly
Missing Sauce Connect local proxy, downloading dependency
This will only happen once.
Downloading 7.16MB
Checksum check for manually overwritten sc version isn't supported.
Unzipping /Users/nathan/Projects/symbiont/wdio-cuke/uat/node_modules/sauce-connect-launcher/sc/sc-latest-osx.zip
Removing /Users/nathan/Projects/symbiont/wdio-cuke/uat/node_modules/sauce-connect-launcher/sc/sc-latest-osx.zip
Sauce Connect downloaded correctly
A service failed in the 'onPrepare' hook
Error: Couldn't read sc permissions: ENOENT: no such file or directory, stat '/Users/nathan/Projects/symbiont/wdio-cuke/uat/node_modules/sauce-connect-launcher/sc/sc-latest-osx/bin/sc'
    at /Users/nathan/Projects/symbiont/wdio-cuke/uat/node_modules/sauce-connect-launcher/lib/sauce-connect-launcher.js:125:34
    at FSReqWrap.oncomplete (fs.js:114:15)

Continue...
ERROR: Couldn't connect to selenium server
chrome
Error
```

Looks like it's trygin to look in the `sc-latest-osx` directory, but it doesn't exist; only `sc-4.4.5-osx` does.

**Comment by christian-bromann** [comment] 2017-04-26 07:45
Duplicate of https://github.com/bermi/sauce-connect-launcher/issues/128 😉

**Closed as completed by christian-bromann** 2017-04-26 07:45 UTC

**Comment by christian-bromann** [comment] 2017-04-26 07:54
FYI: you don't need to set `latest` as SC version. It automatically downloads the latest SC.
