### ISSUE TITLE
Sauce Tunnel Opening, But No Test Running

### ISSUE THREAD

**Issue by brianjoyner** [webdriverio/wdio-sauce-service#13] opened 2016-11-21 23:16 UTC
Finding a potential issue with wdio-sauce-service where a tunnel is being successfully established (confirmed within the Sauce Labs UI), but no test is running.  Within a few minutes, I am returned errors in my terminal telling me, 'ERROR: Couldn't connect to selenium server'.  No other error information is being passed to me.

I have uninstalled and installed wdio-sauce-service as instructed in the readme with the same result.

My wdio.conf file includes the following:

```
services: ['sauce'],
user:   process.env.sauceuser,
key:    process.env.saucepass,
sauceConnect: true,

capabilities: [
     {
        'browserName': 'chrome',
        'platform': 'OS X 10.11',
        'version': 'latest',
        //'build': 'Email-Pixel' 
    },
```

I am able to run tests both via creating a manual tunnel via the instructions given by Sauce Labs and via a non-Sauce Connect settings in wdio.conf

```
// services: ['sauce'],
    user:   process.env.sauceuser,
    key:    process.env.saucepass
//sauceConnect: true,
```

I am also able to run tests when using wdio-sauce-service, BUT setting sauceConnect to false.

```
services: ['sauce'],
user:   process.env.sauceuser,
key:    process.env.saucepass,
sauceConnect: false,
```

**Comment by zinserjan** [comment] 2016-11-26 08:54
@christian-bromann @brianjoyner 

Same issue for me, but I tested only with `wdio-sauce-service`. For me this issue is related to webdriverio `4.4.0`.

webdriverio `4.2.16` works for me, so I think this is an webdriverio issue. Seems to be related to this webdriverio/webdriverio#1683

**Comment by christian-bromann** [comment] 2016-11-28 14:31
Duplicate of webdriverio/webdriverio#1683

**Closed as completed by christian-bromann** 2016-11-28 14:31 UTC
